// Direct team-name -> flag-emoji lookup (not derived from ISO codes) so that
// non-ISO cases (England/Scotland/Wales don't have their own ISO 3166-1
// country code) can share the same simple map. Those three fall back to the
// UK flag as a deliberate simplification.
const TEAM_FLAGS: Record<string, string> = {
  Argentina: '🇦🇷',
  Brazil: '🇧🇷',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Spain: '🇪🇸',
  Portugal: '🇵🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Italy: '🇮🇹',
  England: '🇬🇧',
  Scotland: '🇬🇧',
  Wales: '🇬🇧',
  Ireland: '🇮🇪',
  Croatia: '🇭🇷',
  Poland: '🇵🇱',
  Switzerland: '🇨🇭',
  Austria: '🇦🇹',
  Denmark: '🇩🇰',
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Serbia: '🇷🇸',
  Ukraine: '🇺🇦',
  Turkey: '🇹🇷',
  Greece: '🇬🇷',
  'Czech Republic': '🇨🇿',
  Hungary: '🇭🇺',
  Romania: '🇷🇴',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  Iceland: '🇮🇸',
  Finland: '🇫🇮',
  Morocco: '🇲🇦',
  Senegal: '🇸🇳',
  Nigeria: '🇳🇬',
  Ghana: '🇬🇭',
  Egypt: '🇪🇬',
  Tunisia: '🇹🇳',
  Algeria: '🇩🇿',
  Cameroon: '🇨🇲',
  'Ivory Coast': '🇨🇮',
  'DR Congo': '🇨🇩',
  'Cape Verde': '🇨🇻',
  'South Africa': '🇿🇦',
  Mali: '🇲🇱',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Australia: '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  Qatar: '🇶🇦',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  UAE: '🇦🇪',
  China: '🇨🇳',
  Uzbekistan: '🇺🇿',
  Jordan: '🇯🇴',
  'North Korea': '🇰🇵',
  India: '🇮🇳',
  Canada: '🇨🇦',
  'United States': '🇺🇸',
  Mexico: '🇲🇽',
  'Costa Rica': '🇨🇷',
  Jamaica: '🇯🇲',
  Panama: '🇵🇦',
  Honduras: '🇭🇳',
  Ecuador: '🇪🇨',
  Uruguay: '🇺🇾',
  Colombia: '🇨🇴',
  Chile: '🇨🇱',
  Paraguay: '🇵🇾',
  Venezuela: '🇻🇪',
  Peru: '🇵🇪',
  Bolivia: '🇧🇴',
  'New Zealand': '🇳🇿',
};

export function flagEmoji(team: string): string {
  return TEAM_FLAGS[team] ?? '';
}
